config/routes.rb
FETLOCKER::Application.routes.draw do

  # use this line for regular email/password registration
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  # use this for OAuth providers via OmniAuth gem
  # devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" }

  resources :users do
    resources :lockers
    resources :lockups, only: [:show, :index]
    get :loves, as: "loves"
    get :hates, as: "hates"
  end

  resources :lockers do
    resources :lockups, except: [:index]
  end

  resources :lockups, only: [:index]

  resources :products do
    member do
      get :buy
      get :list
      get :fetch
    end
  end

  resources :searches
  resources :votes, only: [:create]
  
  get "asin/seed", to: "asin#seed"

  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "home#robots", format: :text, as: :robots

  root :to => 'products#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorization_check

  def sitemap
    path = Rails.root.join("public", "sitemaps", "sitemap.xml")
    if File.exists?(path)
      render xml: open(path).read
    else
      render text: "Sitemap not found.", status: :not_found
    end
  end

  def robots
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def signup_button_text
    version =  1 + rand(3)

    case version
    when 1
      return "Sign Up Now!"
    when 2
      return "Get Your #{APP_NAME} On!"
    when 3
      return "Create Your Account!"
    end
  end

end

app/views/home/_logged_out_landing_page.html.erb
<div class="jumbotron text-center">

  <h1><%= APP_NAME %></h1>
  <p class="lead">
    <h3>Create personalized wishlists of the gear you want.<br/></h3>
    <h3><i>Sign up in 15 seconds flat!</i></h3>
  </p>

  <div style="font-size: 1.4em; margin-top: 2em;">
    <%= render 'layouts/signup_form' %>
  </div>

  <div class="row-fluid marketing ">
    <div> <hr class="row sexy-line"> </div>
    <h1 class="text-center">Who <%= APP_NAME %> helps:</h1>

    <div class="span12">
      <div class="span6 text-left small-content-block">
        <h4>Group 1</h4>
        <p>
          Lorem Ipsum 
          <span class="benefit">Benefit goes here!</span>
        </p>
      </div>

      <div class="span6 text-left small-content-block">
        <h4>Group 2</h4>
        <p>Lorem Ipsum
        <span class="benefit">Benefit goes here</span>
        </p>
      </div>
    </div>

    <div class="span12">
      <div class="span6 text-left small-content-block">
        <h4>Group 3</h4>
        <p>Lorem Ipsum
        <span class="benefit">Benefit goes here</span>
        </p>
      </div>

      <div class="span6 text-left small-content-block">
        <h4>Group 4</h4>
        <p>Lorem Ipsum
        <span class="benefit">Benefit goes here</span>
        </p>
      </div>
    </div>

  </div>

<!--   
  <div class="row-fluid marketing text-center span12">
    <div> <hr class="row sexy-line"> </div>
    <h2>How does <%#= APP_NAME %> work?</h2>
  </div>
 -->
</div>

<div class="row-fluid text-center marketing">
  <%= link_to "#{signup_button_text}", "#", :class => "btn btn-danger btn-huge btn-bottom-signup" %>
</div>

app/views/home/index.html.erb
<% provide(:title, "#{APP_NAME}") %>

<% unless current_user %>
  <%# cache "landing_page" do %>
    <%= render "logged_out_landing_page.html.erb" %>
  <%# end %>
<% end %>

app/views/home/robots.text.erb
Sitemap: <%= sitemap_url %>