config/routes.rb
FETLOCKER::Application.routes.draw do

  # use this line for regular email/password registration
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  # use this for OAuth providers via OmniAuth gem
  # devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" }

  resources :users do
    resources :lockers
    resources :lockups, only: [:show, :index]
    get :loves, as: "loves"
    get :hates, as: "hates"
  end

  resources :lockers do
    resources :lockups, except: [:index]
  end

  resources :lockups, only: [:index]

  resources :products do
    member do
      get :buy
      get :list
      get :fetch
    end
  end

  resources :searches
  resources :votes, only: [:create]
  
  get "asin/seed", to: "asin#seed"

  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "home#robots", format: :text, as: :robots

  root :to => 'products#index'
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id               :integer          not null, primary key
#  asin             :string(20)
#  name             :string(255)
#  description      :text
#  price            :float
#  url              :string(255)
#  image_url        :string(255)
#  sales_rank       :integer
#  visibility       :string(255)      default("hidden")
#  created_at       :datetime
#  updated_at       :datetime
#  author           :text
#  binding          :string(255)
#  ean              :string(255)
#  edition          :string(255)
#  isbn             :string(255)
#  item_height      :string(255)
#  item_length      :string(255)
#  item_weight      :string(255)
#  item_width       :string(255)
#  label            :string(255)
#  language         :string(255)
#  formatted_price  :string(255)
#  manufacturer     :string(255)
#  mpn              :string(255)
#  page_count       :string(255)
#  part_number      :string(255)
#  product_group    :string(255)
#  publication_date :string(255)
#  publisher        :string(255)
#  sku              :string(255)
#  studio           :string(255)
#  total_new        :string(255)
#  total_used       :string(255)
#

class Product < ActiveRecord::Base
  has_many :lockups
  has_many :lockers,  :through => :lockups
  has_many :votes,    :dependent => :destroy

  validates :asin, presence: true
  validates :name, :presence => true
  validates_numericality_of :price, :allow_nil => false, :greater_than_or_equal_to => 0

  # default_scope { where("sales_rank IS NOT NULL").order("sales_rank ASC") }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :initialize_asin, only: [:show]
  skip_authorization_check only: [:index, :show, :buy, :search]

  respond_to :html, :json

  def index
    @products = Product.limit(200).order("RAND()").limit(25).order("sales_rank ASC")
    respond_with @products
  end

  def buy
    @product = Product.find(params[:id])
    @client = ASIN::Client.instance
    redirect_to @product.url
  end

  def show
    authorize! :show, Product
    @product = Product.find(params[:id])
    @meta_description = Sanitize.clean(@product.description[0..140]) + '...'

    # grab customer reviews <iframe> url
    resp = @client.lookup(@product.asin, ResponseGroup: :Reviews).first
    @amazon_reviews = resp.raw.CustomerReviews.first[1]

    # grab the items related to the current product
    resp = @client.similar(@product.asin, ResponseGroup: :Small, SimilarityType: :Intersection)
    if resp.any?
      related_asins = resp.collect { |p| p.asin }

      # see if there are any items we need to pull from Amazon
      @related_products = Product.where(asin: related_asins)
      existing_asins = @related_products.pluck(:asin)
      asins_to_fetch = related_asins.delete_if { |a| existing_asins.include?(a) }

      if can? :manage, Product
        # create each product we fetched that doesn't already exist
        if asins_to_fetch.any?
          conn = Connector.new
          fetched_batch = conn.fetch_batch(asins_to_fetch)
          @related_products << fetched_batch
        end
      end
      @related_products = @related_products.all.uniq.take(9)
    else
      @related_products = Product.all.order("sales_rank ASC").limit(9)
    end

    respond_with @product
  end

  def fetch
    authorize! :update, Product
    @product = Product.find(params[:id])
    conn = Connector.new
    conn.fetch_product(@product.asin)
    redirect_to @product
  end

  def new
    authorize! :create, Product
    @product = Product.new
    respond_with @product
  end

  def edit
    authorize! :edit, Product
    @product = Product.find(params[:id])
  end

  def create
    authorize! :create, Product
    @product = Product.create!(product_params)

    flash[:notice] = "Product successfully created!" if @product.save
    respond_with @product
  end

  def update
    authorize! :update, Product
    @product = Product.find(params[:id])

    flash[:notice] = "Product updated!" if @product.update_attributes(product_params)
    respond_with @product 
  end

  def destroy
    authorize! :manage, Product
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product deleted!" if @product.destroy
    redirect_to root_path
  end

  private

    def initialize_asin
      @client = ASIN::Client.instance
    end

    def product_params
      params.require(:product).permit(:description, :image_url, :name, :price, :sku, :asin)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_back_to_products_button.html.erb
<div class="row-fluid text-center marketing">
  <%= link_to "Back to products", { controller: "products", action: "index", random: true }, :class => "btn btn-success btn-huge btn-bottom-signup" %>
</div>

app/views/products/_big_buy_button.html.erb
<%#= link_to "<i class='icon-dollar'></i>#{@product.price.to_i} - Visit Retailer".html_safe, buy_product_path(@product), :class => 'btn btn-buyit btn-buyit-huge', :target => "_blank" %>

<%= link_to "View on Amazon".html_safe, buy_product_path(@product), :class => "btn btn-success btn-huge btn-bottom-signup", :target => "_blank" %>

app/views/products/_big_tumblr_button.html.erb
<% current_page = "#{request.protocol}#{request.host_with_port}#{request.fullpath}" %>
<% product_link = '<a href='"#{current_page}"'><strong>View it on "#{APP_NAME}"</strong></a>' %>

<a href="http://www.tumblr.com/share/photo?source=<%=u "#{@product.full_image_url}" %>&caption=<%= "I need this, I need this, oh baby, oh baby!  " "<strong>#{@product.name}</strong>" + "<br><br>" + 'Check it out on www.example.com: Discover cool gear...' + '<br><br> <a href='"#{current_page}"'><strong>View it on #{APP_NAME}</strong></a>' %>&clickthru=<%=u current_page %>" title="Share on Tumblr" class="btn btn-tumblr btn-tumblr-huge"><i class="icon-tumblr icon-white"></i> Share with Tumblr</a>

app/views/products/_buyit_button.html.erb
<%#= link_to '<i class="icon-dollar"></i> Buy it'.html_safe, product_buy_path(@product), :class => 'btn btn-buyit', :target => "_blank" %>

app/views/products/_email_share_button.html.erb
<a href="myModal" data-toggle="modal" data-target="#myModal" class="btn btn-email"><i class="icon-envelope"></i> Email it</a>

  <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">Fill this out, yo!</h3>
    </div>
    <div class="modal-body">
      <p>Just type an email address & message (don't worry, we already filled it out to make it easy for you) and you're good to go.</p>

      <%= render 'email_share_form' %>
    </div>
  </div>

app/views/products/_email_share_form.html.erb
<%= simple_form_for @email_share, :url => email_shares_path, :html => { :method => :post, :class => 'form-horizontal' } do |f| %> 
  <%= f.error_notification %>

    <%= f.hidden_field :name, :required => true, :value => "#{current_user.username}" %>
    <%= f.input :email, :label => "Recipient's email", :required => true, :class => "text-right", :autofocus => true %>
    <%= f.input :message, as: :text, :required => true %>
    <%= f.input :cool_stuff_antibot, :label => "Anti-spam (leave blank)", :placeholder => "Leave this blank!" %>

    <%= button_tag(type: 'submit', class: "btn btn-primary btn-large") do %>
      <i class="icon-envelope-alt" style="margin-right: 7px;"></i>&nbsp;SEND IT!
    <% end %>

    <button class="btn btn-large" data-dismiss="modal" aria-hidden="true">Close</button>
<% end %>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :image_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/_product_box.html.erb
<div class='product-box shadow rounded'>
  <p>
    <a href="<%= product_path(product) %>">
      <%= image_tag(product.image_url, :class => 'img-polaroid img-fade', :width => 226, title: product.name, alt: product.name ) %>
    </a>
  </p>
  <p style="font-size: 1.5em;" class="text-center"><%= link_to "#{product.name}", product_path(product), title: product.name, alt: product.name %></p>
  <% if can? :manage, Product %>
    <p class="text-right"><%= link_to "(x)", product_path(product), method: :delete, data: { confirm: "Are you sure?" } %></p>
  <% end %>
</div>

app/views/products/_product_box_list.html.erb
<% if !@products.empty? %>

  <% @products.each do |p| %>
    <%# cache [ "product_box", p ] do %>
      <%= render partial: 'product_box', :locals => { :product => p } %>
    <%# end %>
  <% end %>

<% else %>
  
  <% @products = Product.all.order("sales_rank ASC").limit(50) %>
  <% @products.each do |p| %>
    <%# cache [ "product_box", p ] do %>
      <%= render partial: 'product_box', :locals => { :product => p } %>
    <%# end %>
  <% end %>

<% end %>

app/views/products/_related_products_list.html.erb
<div id="products-container" class="transitions-enabled centered clearfix">
  <% @related_products.each do |p| %>
    <%# if Rails.env.production? cache [ "product_box", p ] do %>
    <%= render partial: 'product_box', :locals => { :product => p } %>
    <%# end %>
  <% end %>
</div>

app/views/products/_share_buttons.html.erb
<% current_page = "#{request.protocol}#{request.host_with_port}#{request.fullpath}" %>
<% product_image = "url of the image#{@product.image_url}" %>
<% tags = "tags, go, here" %>

<%= link_to '<i class="icon-dollar"></i> Buy it'.html_safe, buy_product_path(@product), :class => 'btn btn-buyit', :target => "_blank" %>

<a href="http://www.tumblr.com/share/photo?source=<%=u product_image %>&caption=<%= "I need this, I need this, oh baby, oh baby!" " <strong>#{@product.name}</strong>" + "<br><br>" + "Check it out on www.example.com: Where Pinterest meets gear." + "<br><br>#{current_page}" %>&clickthru=<%=u current_page %>" title="Share on Tumblr" class="btn btn-tumblr"><i class="icon-tumblr icon-white"></i> Tumbl it</a>

<a href="//pinterest.com/pin/create/button/?url=<%=u current_page %>&media=<%= product_image %>&description=<%=u "I need this, I need this, oh baby, oh baby!" " <strong>#{@product.name}</strong>" + "<br><br>" + "Check it out on www.example.com: Where Pinterest meets gear." + "<br><br>#{current_page}" %>" data-pin-config="none" target="_blank" class="btn btn-pinterest"><i class="icon-pinterest icon-white"></i> Pin it</a>

<a href="http://twitter.com/share?url=<%= current_page %>&text=<%= "Will someone buy this for me? " + @product.name + " #{current_page} " %>&via=<%= "twitterhandlewithout@sign" %>&related=<%= "other, twitter, accounts" %>&hashtags=<%= tags %>" class="btn btn-twitter" target="_blank"><i class="icon-twitter"></i> Tweet it</a> 



<%# if current_user %>
  <%#= render 'email_share_button' %>
<%# end %>

<!-- Crazy Pinterest multi-image layout -->

<!-- <a href='javascript:void((function()%7Bvar%20e=document.createElement(&apos;script&apos;);e.setAttribute(&apos;type&apos;,&apos;text/javascript&apos;);e.setAttribute(&apos;charset&apos;,&apos;UTF-8&apos;);e.setAttribute(&apos;src&apos;,&apos;http://assets.pinterest.com/js/pinmarklet.js?r=&apos;+Math.random()*99999999);document.body.appendChild(e)%7D)());' class="btn btn-pinterest"><i class="icon-pinterest"></i> Pinterest</a> -->

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/list.html.erb
<div class='row'>
<h1>Listing products</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Image url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.price %></td>
    <td><%= product.image_url %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>
</div>

app/views/products/show.html.erb
<% provide(:title, "#{@product.name}") %>
<% provide(:description, "#{@meta_description}") %>

<% if can? :manage, Product %>
  <p>
    <%= link_to "Fetch", fetch_product_path(@product) %> |
    <%= link_to 'Edit', edit_product_path(@product) %> | 
    <%= link_to "Delete", product_path(@product), data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<h1 class="text-center" style="margin-bottom: .5em;"> <%= @product.name %> </h1>

<div class="row-fluid">
  <div id="product-image" class="span5 text-center">
    <a href='<%= buy_product_path(@product) %>' target="_blank", caption='<%= "Buy #{@product.name}" %>', title='<%= "Buy #{@product.name}" %>'>
    <%= image_tag(@product.image_url, :class => 'img-polaroid img-fade', :alt => "#{@product.name}") %>
    </a>

    <div id="product-details" class="text-left">
      <h3 class="text-center">Product Details:</h3>
      
      <p><b>ASIN: </b><%= @product.asin %></p>

      <% if @product.author %>
        <p><b>Author(s):</b> <%= @product.author %></p>
      <% end %>

      <% if @product.binding %>
        <p><b>Binding:</b> <%= @product.binding %></p>
      <% end %>

      <% if @product.ean %>
        <p><b>EAN:</b> <%= @product.ean %></p>
      <% end %>

      <% if @product.edition %>
        <%# TODO: figure out why ordinalize() isn't working %>
        <p><b>Edition:</b> <%= @product.edition %></p>
      <% end %>

      <% if @product.price.to_i > 0 %>
        <p>
          <b>Price:</b>  <%= number_to_currency(@product.price, precision: 2) %>
        </p>
      <% end %>

      <% if @product.isbn %>
        <p><b>ISBN:</b> <%= @product.isbn %></p>
      <% end %>

      <%#
        item_height: r.item_height,
        item_length: r.item_length,
        item_weight: r.item_weight,
        item_width: r.item_width,
      %>

      <% if @product.label %>
        <p><b>Label:</b> <%= @product.label %></p>
      <% end %>

      <% if @product.language %>
        <p><b>Language:</b> <%= @product.language %></p>
      <% end %>

      <% if @product.manufacturer %>
        <p><b>Manufacturer:</b> <%= @product.manufacturer %></p>
      <% end %>

      <% if @product.mpn %>
        <p><b>MPN:</b> <%= @product.mpn %></p>
      <% end %>

      <% if @product.page_count %>
        <p><b>Page Count:</b> <%= @product.page_count %></p>
      <% end %>

      <% if @product.part_number %>
        <p><b>Part #:</b> <%= @product.part_number %></p>
      <% end %>

      <% if @product.product_group %>
        <p><b>Category:</b> <%= @product.product_group %></p>
      <% end %>

      <% if @product.publication_date %>
        <p><b>Publication Date:</b> <%= @product.publication_date %></p>
      <% end %>

      <% if @product.publisher %>
        <p><b>Publisher:</b> <%= @product.publisher %></p>
      <% end %>

      <% if @product.sku %>
        <p><b>SKU:</b> <%= @product.sku %></p>
      <% end %>

      <% if @product.studio %>
        <p><b>Studio:</b> <%= @product.studio %></p>
      <% end %>

      <% if @product.total_new %>
        <p><b>In Stock:</b> <span style="color: #009361;">Oh yeah!</span></p>
      <% end %>
    </div>
  </div>

  <div id="product-description" class="span7">
    <div>
      <%= link_to "View on Amazon".html_safe, buy_product_path(@product), :class => 'btn btn-buyit', style: "margin-bottom: 0em; width: 350px; font-size: 40px; padding: 1em;", :target => "_blank" %>
    </div>
    <div id="description-text" class="text-left", style="margin-top: 1em;">
      <%= @product.description.html_safe %>
    </div>
  </div>
</div>


<div class="text-center row-fluid">
  <%= render 'big_buy_button' %>
</div>

<div><hr class="sexy_line"></div>

<h2 class="text-center">You may also like:</h2>
<%= render 'related_products_list' %>

<div class="text-center row-fluid">
  <%= render 'big_buy_button' %>
</div>

<div id="amazon-reviews">
  <h2>Amazon Reviews</h2>
  <iframe src="<%= @amazon_reviews %>">
    <p>Your browser does not support iframes.</p>
  </iframe>
</div>

<%= render 'products/back_to_products_button' %>

<% if can? :manage, Product %>
<p>
  <%= link_to "Fetch", fetch_product_path(@product) %> |
  <%= link_to 'Edit', edit_product_path(@product) %> | 
  <%= link_to "Delete", product_path(@product), data: { confirm: 'Are you sure?' } %>
</p>
<% end %>