config/routes.rb
FETLOCKER::Application.routes.draw do

  # use this line for regular email/password registration
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  # use this for OAuth providers via OmniAuth gem
  # devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" }

  resources :users do
    resources :lockers
    resources :lockups, only: [:show, :index]
    get :loves, as: "loves"
    get :hates, as: "hates"
  end

  resources :lockers do
    resources :lockups, except: [:index]
  end

  resources :lockups, only: [:index]

  resources :products do
    member do
      get :buy
      get :list
      get :fetch
    end
  end

  resources :searches
  resources :votes, only: [:create]
  
  get "asin/seed", to: "asin#seed"

  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "home#robots", format: :text, as: :robots

  root :to => 'products#index'
end

app/views/layouts/_asin_fill.html.erb
<% if current_user && (can? :manage, Product) %>
  <li>
    <%= link_to "Fill All", { controller: 'asin', action: 'fill', all: true } %>
  </li>
<% end %>

app/views/layouts/_dropdown.html.erb
 <li class="dropdown">
  <a href="#" class="dropdown-toggle active" data-toggle="dropdown">Categories<b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li><%= link_to "Category 1", "/wherever" %></li>
    <li><%= link_to "Category 2", "/wherever" %></li>
    <li><%= link_to "Category 3", "/wherever" %></li>
    <li><%= link_to "Category 4", "/wherever" %></li>
  </ul>
</li>

app/views/layouts/_footer.html.erb
<div id='footer' class='text-center'>
  <hr class='sexy_line'>
  <p>Copyright <%= Time.now.year %> <%= link_to "#{APP_NAME}", '/' %></p>
<!--   <p>
    <a href="https://mixpanel.com/f/partner" target="_blank"><img src="//cdn.mxpnl.com/site_media/images/partner/badge_light.png" alt="Mobile Analytics" /></a>
  </p> -->
</div>

app/views/layouts/_ga_development.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46128351-5', {
    'cookieDomain': 'none'
  });
  ga('send', 'pageview');
</script>

app/views/layouts/_ga_production.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46128351-4', "codingoncoffee.com");
  ga('send', 'pageview');

</script>

app/views/layouts/_login_signup_banner.html.erb
<div id="login-signup">
  
  <div class='row-fluid'>
    <div class='span7'>
      <span class='tagline'><%= "#{APP_NAME} helps you discover cool stuff." %></span><br>
      <span class='call-to-action'>Sign up with now to store and share the stuff you like.</span>
    </div>
    
    <div class='span5 text-center'>
      <%= link_to "Join Now", new_user_registration_path, :class => 'btn btn-large btn-danger' %>
      <%= link_to 'Log In', new_user_session_path, :class => 'btn btn-large ' %>
    </div>

    <!-- Uncomment for Tumblr or future OAuth registration strategies -->
    <!-- <div class='span5 text-center'> -->
      <%#= link_to "Sign in with Tumblr", user_omniauth_authorize_path(:tumblr), :class => 'btn btn-large btn-tumblr' %>
    <!-- </div> -->
  </div>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="messages text-center alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_search_form.html.erb
<% @search = Search.new %>
<%= form_for @search, :class => 'form-inline' do |f| %>
    <%= f.text_field :keywords %>
    <%= f.submit "Search", :class => 'btn btn-primary' %>
<% end %>

app/views/layouts/_navbar.html.erb
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "#{APP_NAME}", root_path, :class => 'brand' %>
        <ul class="nav">
          <%#= render 'dropdown' %>
          <li><%#= link_to "Lookup", asin_lookup_path %></li>
          <%#= render 'asin_fill' %> 
        </ul>
        
        <%= render 'layouts/nav_search_form' %>

        <%# if current_user %>
<!--           <ul class="nav pull-right">
            <li><%#= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          </ul> -->
        <%# end %>
      </div>
    </div><!-- /navbar-inner -->
  </div><!-- /navbar -->

app/views/layouts/_navbar_tumblr_button.html.erb
<!-- A 'share on Tumblr' button used to live in the top navbar. Use this for whatever you want. -->

<ul class="nav tumblr-button">
<a href="http://www.tumblr.com/share/link?url=<%=u "http://www.example.com" %>&name=<%=u "#{APP_NAME} - #{APP_TITLE_DESCRIPTION}" %>&description=<%=u "#{APP_META_DESCRIPTION}" %>" title="Share on Tumblr" class="btn btn-tumblr"><i class="icon-tumblr icon-white"></i> Share on Tumblr</a>
</ul>

app/views/layouts/_signup_form.html.erb
<%= simple_form_for(resource, :url => registration_path(resource_name), :html => {:class => 'form-horizontal' }) do |f| %>
  <% f.object.lockers.build if resource.lockers.empty? %>
  <%= f.error_notification %>
  <%= f.input :username, :autofocus => true, :placeholder => "Letters and numbers only" %>
  <%= f.input :email, :required => true, :placeholder => "Valid email address" %>
  <%= f.input :password, :required => true, :placeholder => "Uber-secret password, 8 character min" %>
  <%= f.button :submit, 'Start stuffing your lockers!', :id => "submit", :class => 'btn-danger btn-huge' %>
<% end %>

<p class='in-or-out'> - or - </p>

<%= link_to 'Log In', new_user_session_path, :class => 'btn btn-huge btn-log-in' %>

app/views/layouts/_uservoice.html.erb
<!-- Place your UserVoice widget code here & set it up how you'd like -->
<!-- FYI: Google Analytics event tracking is already set up in application.js  -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)).html_safe %></title>
  <meta name="description" content="<%= meta_description(yield(:description)).html_safe %>">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/ga_production' if Rails.env.production? %>
  <%= render 'layouts/ga_development' if !Rails.env.production? %>
  <%#= render 'layouts/uservoice' %>
</head>

<body>
  <%= render 'layouts/navbar' %>

  <% if current_page?(products_path) || 
    current_page?(lockers_path) || 
    current_page?(lockups_path) ||
    current_page?(root_path) 
  %>
    <div class="container-narrow">
  <% else %>
    <div class='container-narrow shadow rounded' style='width: 780px; border: 1px solid black; background-color: white; margin-top: 2em; padding: 2em;'>
  <% end %>

  <%= render 'layouts/messages' %>

  <%= yield %>

  </div> 

  <%= render 'layouts/footer' %>

</body>
</html>